name: "🐛 Bug Report"
description: "Сообщить об ошибке"
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Четко опишите, что происходит не так
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Шаги для воспроизведения
      description: Как воспроизвести проблему?
      placeholder: |
        1. Выполнить команду...
        2. Получить ошибку...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Версия
      description: Какая версия пакета?
    validations:
      required: true
