name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*_*.*.*"

jobs:
  verify:
    uses: ./.github/workflows/ci.yml

  release:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build

      - name: Determine if dev release
        id: dev_check
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+_[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_dev=true" >> $GITHUB_OUTPUT
            echo "npm_tag=dev" >> $GITHUB_OUTPUT
          else
            echo "is_dev=false" >> $GITHUB_OUTPUT
            echo "npm_tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: |
          if [[ "${{ steps.dev_check.outputs.is_dev }}" == "true" ]]; then
            echo "🚀 Публикация dev релиза с тегом '${{ steps.dev_check.outputs.npm_tag }}'"
            npm publish --tag ${{ steps.dev_check.outputs.npm_tag }}
          else
            echo "🚀 Публикация обычного релиза с тегом '${{ steps.dev_check.outputs.npm_tag }}'"
            npm publish --tag ${{ steps.dev_check.outputs.npm_tag }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
