name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Тип обновления версии"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      custom_version:
        description: "Кастомная версия (опционально, переопределяет version_type). Формат: v1.2.3"
        required: false
        type: string
      is_dev_release:
        description: "Создать dev релиз (формат: v0.0.0_1.2.3)"
        required: false
        default: false
        type: boolean
      base_version:
        description: "Базовая версия для dev релиза (например, v1.0.0). Используется только если is_dev_release = true"
        required: false
        default: "v0.0.0"
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.new_version.outputs.version }}
      tag: ${{ steps.new_version.outputs.tag }}
      is_dev: ${{ steps.new_version.outputs.is_dev }}
      npm_tag: ${{ steps.new_version.outputs.npm_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Настроить Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Получить текущую версию
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Вычислить новую версию
        id: new_version
        run: |
          if [ "${{ inputs.is_dev_release }}" = "true" ]; then
            # Логика dev релиза
            BASE_VERSION="${{ inputs.base_version }}"
            BASE_VERSION=${BASE_VERSION#v}  # Убираем префикс 'v' если есть

            if [ "${{ inputs.custom_version }}" != "" ]; then
              # Используем кастомную dev версию
              DEV_VERSION="${{ inputs.custom_version }}"
              DEV_VERSION=${DEV_VERSION#v}
            else
              # Вычисляем dev версию
              CURRENT="${{ steps.current_version.outputs.current }}"
              IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

              case "${{ inputs.version_type }}" in
                "major")
                  MAJOR=$((MAJOR + 1))
                  MINOR=0
                  PATCH=0
                  ;;
                "minor")
                  MINOR=$((MINOR + 1))
                  PATCH=0
                  ;;
                "patch")
                  PATCH=$((PATCH + 1))
                  ;;
              esac
              DEV_VERSION="$MAJOR.$MINOR.$PATCH"
            fi

            echo "version=$DEV_VERSION" >> $GITHUB_OUTPUT
            echo "tag=v${BASE_VERSION}_${DEV_VERSION}" >> $GITHUB_OUTPUT
            echo "is_dev=true" >> $GITHUB_OUTPUT
            echo "npm_tag=dev" >> $GITHUB_OUTPUT
          else
            # Логика обычного релиза
            if [ "${{ inputs.custom_version }}" != "" ]; then
              # Используем кастомную версию
              NEW_VERSION="${{ inputs.custom_version }}"
              NEW_VERSION=${NEW_VERSION#v}
              echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
              echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT
            else
              # Вычисляем обновление версии
              CURRENT="${{ steps.current_version.outputs.current }}"
              IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

              case "${{ inputs.version_type }}" in
                "major")
                  MAJOR=$((MAJOR + 1))
                  MINOR=0
                  PATCH=0
                  ;;
                "minor")
                  MINOR=$((MINOR + 1))
                  PATCH=0
                  ;;
                "patch")
                  PATCH=$((PATCH + 1))
                  ;;
              esac

              NEW_VERSION="$MAJOR.$MINOR.$PATCH"
              echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
              echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT
            fi
            echo "is_dev=false" >> $GITHUB_OUTPUT
            echo "npm_tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Обновить версию в package.json
        run: |
          if [ "${{ steps.new_version.outputs.is_dev }}" = "false" ]; then
            npm version ${{ steps.new_version.outputs.version }} --no-git-tag-version
          else
            echo "📋 Пропускаем обновление package.json для dev релиза"
          fi

      - name: Зафиксировать изменение версии
        run: |
          if [ "${{ steps.new_version.outputs.is_dev }}" = "false" ]; then
            git add package.json
            git commit -m "chore: bump version to ${{ steps.new_version.outputs.version }}"
            git push origin main
          else
            echo "📋 Пропускаем коммит для dev релиза"
          fi

      - name: Создать и отправить тег
        run: |
          git tag ${{ steps.new_version.outputs.tag }}
          git push origin ${{ steps.new_version.outputs.tag }}

  verify:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci

      - name: Запустить проверки
        run: |
          npm run verify
          npm run test:coverage

      - name: Загрузить покрытие в Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  publish:
    needs: [prepare-release, verify]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - name: Собрать проект
        run: npm run build

      - name: Проверить аутентификацию NPM
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "❌ NPM_TOKEN не установлен в GitHub Secrets!"
            exit 1
          fi
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Опубликовать в npm
        run: |
          if [[ "${{ needs.prepare-release.outputs.is_dev }}" == "true" ]]; then
            echo "🚀 Публикация dev релиза с тегом '${{ needs.prepare-release.outputs.npm_tag }}'"
            npm publish --tag ${{ needs.prepare-release.outputs.npm_tag }}
          else
            echo "🚀 Публикация обычного релиза с тегом '${{ needs.prepare-release.outputs.npm_tag }}'"
            npm publish --tag ${{ needs.prepare-release.outputs.npm_tag }}
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Создать GitHub релиз
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.tag }}
          release_name: Release ${{ needs.prepare-release.outputs.tag }}
          draft: false
          prerelease: ${{ needs.prepare-release.outputs.is_dev == 'true' }}
          body: |
            Release ${{ needs.prepare-release.outputs.tag }}

            ${{ needs.prepare-release.outputs.is_dev == 'true' && '🚧 **Dev Release** - Это экспериментальная версия для тестирования' || '🚀 **Stable Release**' }}

            ## Изменения
            ${{ needs.prepare-release.outputs.is_dev == 'true' && format('- Dev версия: {0}', needs.prepare-release.outputs.version) || format('- Обновление версии до {0}', needs.prepare-release.outputs.version) }}

            ✅ **Статус**: Релиз успешно опубликован!
            📦 **NPM**: Опубликовано с тегом `${{ needs.prepare-release.outputs.npm_tag }}`

  cleanup-on-failure:
    needs: [prepare-release, verify]
    runs-on: ubuntu-latest
    if: failure()
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настроить Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Удалить тег при неудаче
        run: |
          echo "❌ CI проверки провалились, удаляем тег ${{ needs.prepare-release.outputs.tag }}"
          git push --delete origin ${{ needs.prepare-release.outputs.tag }} || echo "Тег уже удален"

      - name: Откатить коммит версии (если был)
        run: |
          if [ "${{ needs.prepare-release.outputs.is_dev }}" = "false" ]; then
            echo "↩️ Откатываем коммит с версией для обычного релиза"
            git reset --hard HEAD~1
            git push --force-with-lease origin main
          else
            echo "📋 Нечего откатывать для dev релиза"
          fi
