name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Тип обновления версии"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.new_version.outputs.version }}
      tag: ${{ steps.new_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Настроить Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Получить текущую версию
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Вычислить новую версию
        id: new_version
        run: |
          CURRENT="${{ steps.current_version.outputs.current }}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          case "${{ inputs.version_type }}" in
            "major")
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            "minor")
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            "patch")
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Обновить версию в package.json
        run: |
          npm version ${{ steps.new_version.outputs.version }} --no-git-tag-version

      - name: Создать и отправить тег
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ steps.new_version.outputs.version }}"
          git tag ${{ steps.new_version.outputs.tag }}
          git push origin ${{ steps.new_version.outputs.tag }}

  verify:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci

      - name: Запустить проверки
        run: |
          npm run verify
          npm run test:coverage

      - name: Загрузить покрытие в Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  publish:
    needs: [prepare-release, verify]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - name: Собрать проект
        run: npm run build

      - name: Настроить NPM аутентификацию
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "❌ NPM_TOKEN не установлен в GitHub Secrets!"
            exit 1
          fi
          echo "✅ NPM_TOKEN получен (длина: ${#NPM_TOKEN})"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "📝 .npmrc файл создан"
          cat ~/.npmrc | sed 's/:_authToken=.*/:_authToken=***СКРЫТ***/'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Опубликовать в npm
        run: |
          echo "🔍 Проверяем информацию о публикации..."
          npm whoami || echo "⚠️ npm whoami не удался, но продолжаем..."
          echo "📋 Содержимое package.json (имя и версия):"
          node -e "const pkg = require('./package.json'); console.log('Name:', pkg.name); console.log('Version:', pkg.version);"

          echo "🚀 Публикация в npm..."
          npm publish --access public --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Создать GitHub релиз
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.tag }}
          release_name: Release ${{ needs.prepare-release.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            🚀 **Release ${{ needs.prepare-release.outputs.tag }}**

            ## Изменения
            - Обновление версии до ${{ needs.prepare-release.outputs.version }}

            ✅ **Статус**: Релиз успешно опубликован!
            📦 **NPM**: Опубликовано с тегом `latest`

  update-main:
    needs: [prepare-release, publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Настроить Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Пушить обновление версии в main
        run: |
          # Переключаемся на main и мерджим изменения из тега
          git checkout main
          git merge --no-ff ${{ needs.prepare-release.outputs.tag }} -m "chore: release ${{ needs.prepare-release.outputs.tag }}"
          git push origin main

  cleanup-on-failure:
    needs: [prepare-release, verify]
    runs-on: ubuntu-latest
    if: failure()
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настроить Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Удалить тег при неудаче
        run: |
          echo "❌ CI проверки провалились, удаляем тег ${{ needs.prepare-release.outputs.tag }}"
          git push --delete origin ${{ needs.prepare-release.outputs.tag }} || echo "Тег уже удален"

      - name: Очистка при неудаче
        run: |
          echo "🧹 Неудачный релиз - тег ${{ needs.prepare-release.outputs.tag }} уже удален"
          echo "📋 Main ветка не изменялась, откат не требуется"
